name: tic_tac_toe
description: A Tic Tac Toe game built with Flutter.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  go_router: ^17.0.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.2
  dartz: ^0.10.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  build_runner: ^2.10.4
  riverpod_generator: ^4.0.0+1
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoRegular.ttf
    - family: PermanentMarker
      fonts:
        - asset: assets/fonts/PermanentMarker.ttf
